name: 'Sentry Artifacts'
description: 'Handles uploading coverage/test artifacts to codecov'

inputs:
  files:
    description: 'Path to coverage file(s) - comma separated for multiple files'
    default: '.artifacts/*.coverage.xml'
    required: true
  test_result_files:
    description: 'Path to test result file(s) - comma separated for multiple files'
    default: '.artifacts/*.junit.xml'
    required: true
  type:
    description: 'The type of change (frontend, backend)'
    default: 'backend'
    required: false
  token:
    description: 'The codecov token'
    required: true
  commit_sha:
    description: 'The commit sha'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download and Verify Codecov CLI
      run: |
        ./.github/actions/artifacts/download-codecov-cli.sh
    - name: Upload Coverage
      continue-on-error: true
      run: |
        ./.github/actions/artifacts/do-upload.sh
